version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pitwall_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pitwall_admin
      POSTGRES_PASSWORD: pitwall_admin
      POSTGRES_DB: pitwall
    volumes:
      - pitwall_pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pitwall_admin -d pitwall"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pitwall_pgdata:

